### PR TITLE
Collapse sentences that are coded with the same code into one “turn” on the TurnTaking visualization

### PR DESCRIPTION
**Pull request by neilthawani**
Related issue: https://github.com/neilthawani/classinsight-prototype/issues/29
Related merged PR: https://github.com/neilthawani/classinsight-prototype/pull/201

Current status - display 3 turns of the transcript on bar row click:
image

### CODE REVIEW

**Comment by neilthawani** [comment]
Currently the collapsing works:
image

The width of the bars in the code originally was multiplied by 6:
image

That functionality was changed to just a multiplier of 1:
image

I think it would be nice to hover over the "row" containing the bars and get the transcript data, so that it clearly indicates which row they're hovering over and there is a box overlaid on the screen which displays the transcript text.

image

I would like input on this proposed functionality and also bars that extend beyond the width of the chart:
image

How should we handle those bars? It would be good to communicate that this is an extremely long length of <code>, but I don't think I want to cut it off at the bounds of the chart, nor do I like how it currently looks.

**Comment by neilthawani** [comment]
I'll need to adjust the collapsed view timestamps too.

**Comment by AndiGomoll** [comment]
> Currently the collapsing works:
> image
> 
> The width of the bars in the code originally was multiplied by 6:
> image
> 
> That functionality was changed to just a multiplier of 1 (number of tokens per utterance/bar):
> image
> 
> I would like input on bars that extend beyond the width of the chart:
> image
> 
> Taking into account the width of text for time ranges too:
> image
> 
> How should we handle those bars? It would be good to communicate that this is an extremely long length of `code`, but I don't think I want to cut it off at the bounds of the chart, nor do I like how it currently looks.

Great question! One thing we talked about yesterday with our team was if we might use the number of words in the full (collapsed) turn to determine bar length rather than time. Could this help to shorten the bars? 

I agree that it doesn't make sense to extend over the key. It may make sense to have a cut off point. Teachers can still recognize which turns were longest and the overall cadence of the lesson, so I think that tradeoff with perfect accuracy is a fine one.

**Comment by neilthawani** [comment]
> Great question! One thing we talked about yesterday with our team was if we might use the number of words in the full (collapsed) turn to determine bar length rather than time. Could this help to shorten the bars?

Perhaps unfortunately, that's how this currently works.

> I agree that it doesn't make sense to extend over the key. It may make sense to have a cut off point. Teachers can still recognize which turns were longest and the overall cadence of the lesson, so I think that tradeoff with perfect accuracy is a fine one.

Perhaps we'll cut the length at the max-width of the chart and do a "word count on hover" ... I'll experiment with this. Thanks.

**Comment by neilthawani** [comment]
The data here's a little inconsistent. Perhaps we can ask teachers if they would find hover-over feedback on the turn taking bars...

**Comment by neilthawani** [comment]
image

**Pull request merged**
